version: '3'

services:

    nginx:
        image: nginx:1.17-alpine
        ports:
            - 8080:80
        links:
            - php
    php:
#        image: php:fpm-alpine
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
