version: '3'

services:

    php:
        #        image: php:fpm-alpine
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile

    nginx:
#        image: nginx:1.17-alpine
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 8080:80

